export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL'
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR'

export const LOAD_TODOS_SUCCESS = 'LOAD_TODOS_SUCCESS'
export const UPDATE_TODO_SUCCESS = 'UPDATE_TODO_SUCCESS'

export const ADD_NOTIFICATION_SUCCESS = 'ADD_NOTIFICATION_SUCCESS'
export const LOAD_NOTIFICATIONS_SUCCESS = 'LOAD_NOTIFICATIONS_SUCCESS'

export const LOAD_STUDENTS_SUCCESS = 'LOAD_Students_SUCCESS'

export const SHOW_ADD_TODO_MODAL = 'SHOW_ADD_TODO_MODAL'
export const HIDE_ADD_TODO_MODAL = 'HIDE_ADD_TODO_MODAL'
